INSERT INTO film(fid,Title,yr,genre) VALUES (1,'Heartbeat',1980,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (2,'Friday the 13th',1980,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (3,'The Hearse',1980,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (4,'Middle-age Crazy',1980,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (5,'The Kidnapping of the President',1980,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (6,'McVicar',1980,'BioPic');
INSERT INTO film(fid,Title,yr,genre) VALUES (7,'Little Darlings',1980,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (8,'Airplane!',1980,'Comd, Disa');
INSERT INTO film(fid,Title,yr,genre) VALUES (9,'Hide in Plain Sight',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (10,'Battle Beyond the Stars',1980,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (11,'How to Beat the High Cost of Living',1980,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (12,'Just Before Dawn',1980,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (13,'Die Laughing',1980,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (14,'Carny',1980,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (15,'Fiendish Plot of Fu Manchu',1980,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (16,'Tatoo',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (17,'Ordinary People',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (18,'The Idolmaker',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (19,'Little Miss Marker',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (20,'Xanadu',1980,'Fant, Musc');
INSERT INTO film(fid,Title,yr,genre) VALUES (21,'Where the Buffalo Roam',1980,'Noir');
INSERT INTO film(fid,Title,yr,genre) VALUES (22,'The Incredible Shrinking Woman',1980,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (23,'The Black Hole',1980,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (24,'Simon',1980,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (25,'The Fan',1980,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (26,'Shogun Assassin',1980,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (27,'The Long Good Friday',1980,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (28,'Loophole',1980,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (29,'Borderline',1980,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (30,'The Adventures of Picasso',1980,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (31,'Caddyshack',1980,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (32,'The Assault',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (33,'Friday the 13th ... The Orphan',1980,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (34,'Silent Scream',1980,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (35,'Prom Night',1980,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (36,'Terror Train',1980,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (37,'The Great Rock and Roll Swindle',1980,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (40,'Falling in Love Again',1980,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (41,'Flash Gordon',1980,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (42,'The Legend of Walks Far Woman',1980,'West');
INSERT INTO film(fid,Title,yr,genre) VALUES (43,'Forgotten Prisoners',1980,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (44,'Gideon''s Trumpet',1980,'#NAME?');
INSERT INTO film(fid,Title,yr,genre) VALUES (45,'title',1980,'genre');
INSERT INTO film(fid,Title,yr,genre) VALUES (46,'Hero at Large',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (47,'The Dogs of War',1980,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (48,'Goodbye Pork Pie',1980,'Adgenre');
INSERT INTO film(fid,Title,yr,genre) VALUES (49,'Used Cars',1980,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (50,'Missing',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (51,'Meatballs part II',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (52,'Maenner',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (53,'The Mango Tree',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (54,'The Gunslinger',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (55,'Naked Massacre',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (56,'Touch and Go',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (57,'Mad Dog',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (58,'Lianna',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (59,'Baby, It''s You',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (60,'Brussels Transit',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (61,'Black Stallion',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (62,'Take It To The Limit',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (63,'My Bodyguard',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (64,'From Hell to Vigenreory',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (65,'Stuckey''s Last Stand',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (66,'Wholly Moses',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (67,'Touched by Love',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (68,'Union City',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (69,'Seems Like Old Times',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (70,'Lifepod',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (71,'The Ogenreagon',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (72,'Return of the Secaucus 7',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (73,'The Awakening',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (74,'Massacre at Central High',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (75,'Wilma',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (76,'Terraces',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (77,'Stalk the Wild Child',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (78,'Hey, I''m Alive',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (79,'Greaser''s Palace',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (80,'Meatballs part III',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (81,'C.H.U.D.',1980,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (82,'Best Boy',1980,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (83,'Through the Wire',1980,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (84,'Red Sorghum',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (85,'Moscow Does Not Believe in Tears',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (86,'The Competition',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (87,'Over the Edge',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (88,'La Boum',1980,'Dram, Romt');
INSERT INTO film(fid,Title,yr,genre) VALUES (89,'Brother From Another Planet',1980,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (90,'Extraterrestrial Terror',1980,'ScFi,Horr');
INSERT INTO film(fid,Title,yr,genre) VALUES (91,'Fade to Black',1980,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (92,'The Exterminator',1980,'Viol');
INSERT INTO film(fid,Title,yr,genre) VALUES (93,'Le Conte de Monte Christo',1980,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (94,'Dark Passion',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (95,'Imagine the Sound',1981,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (96,'Hell Night',1981,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (97,'Galaxy of Terror',1981,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (98,'The Final Confligenre',1981,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (99,'Celeste',1981,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (100,'Lords of Discipline',1981,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (102,'Butterfly',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (103,'Clash of the Titans',1981,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (104,'Halloween II',1981,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (105,'Serial',1981,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (106,'Paternity',1981,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (107,'So Fine',1981,'Agenren,Comd');
INSERT INTO film(fid,Title,yr,genre) VALUES (108,'For Your Eyes Only',1981,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (109,'All Night Long',1981,'aw');
INSERT INTO film(fid,Title,yr,genre) VALUES (110,'Devil and Max Devlin',1981,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (111,'Arthur',1981,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (112,'Caveman',1981,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (113,'Bustin'' Loose',1981,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (114,'Venom',1981,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (115,'Eye of the Needle',1981,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (116,'The Double McGuffin',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (117,'Ms.~45',1981,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (118,'Power Play',1981,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (119,'Bushido Blade',1981,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (120,'Search and Destroy',1981,'Axtn');
INSERT INTO film(fid,Title,yr,genre) VALUES (121,'Honeymoon in Vegas',1981,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (122,'Modern Problems',1981,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (123,'Lovers and Liars',1981,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (124,'Ticket to Heaven',1981,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (125,'Threshold',1981,'Docu,Dram');
INSERT INTO film(fid,Title,yr,genre) VALUES (126,'A Dangerous Summer',1981,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (127,'Take this Job and Shove it',1981,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (128,'Improper Channels',1981,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (129,'East of Elephant Rock',1981,'H');
INSERT INTO film(fid,Title,yr,genre) VALUES (130,'Friday the 13th Part II',1981,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (131,'Student Bodies',1981,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (132,'Night the Lights Went Out in Georgia',1981,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (134,'Diva',1981,'Romt,Susp');
INSERT INTO film(fid,Title,yr,genre) VALUES (135,'Green Ice',1981,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (136,'Road Games',1981,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (137,'Visiting Hours',1981,'Susp,Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (138,'Chariots of Fire',1981,'AA');
INSERT INTO film(fid,Title,yr,genre) VALUES (139,'Das Boot',1981,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (140,'Spetters',1981,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (141,'Oppenheimer',1981,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (142,'La Che\`evre',1981,'Cops and Robbers');
INSERT INTO film(fid,Title,yr,genre) VALUES (143,'Vito Rossi',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (144,'Candy',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (145,'Mephisto',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (146,'Taxi zum Klo',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (147,'Lonely Hearts',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (148,'Attack Force Z',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (149,'Raggedy Man',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (150,'Don''t Cry It''s Only Thunder',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (151,'Nobody''s Perfekt',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (152,'Nighthawks',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (153,'Ghost Story',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (154,'Body and Soul',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (155,'Deadline',1981,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (156,'This is Elvis',1981,'Docu,Musc');
INSERT INTO film(fid,Title,yr,genre) VALUES (157,'Petrole',1981,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (158,'Utu',1981,'Epic');
INSERT INTO film(fid,Title,yr,genre) VALUES (159,'Fear No Evil',1981,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (160,'Basket Case',1981,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (161,'Mortuary',1981,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (162,'Heartaches',1981,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (163,'Night Gallery',1981,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (164,'Dial M for Murder',1981,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (165,'Death of a Centerfold: the Dorothy Stratten Story',1981,'Dram, BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (166,'Labyrinth of Passion',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (167,'Things Are Tough All Over',1982,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (168,'Poetry in Motion',1982,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (169,'Stuck on You!',1982,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (170,'Chan is Missing',1982,'Myst');
INSERT INTO film(fid,Title,yr,genre) VALUES (171,'Table for Five',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (172,'The Sword and the Sorcerer',1982,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (173,'Fighting Back',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (174,'Young Dogenreors in Love',1982,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (175,'My Favourite yr',1982,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (176,'That Championship Season',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (177,'An Officer and a Gentleman',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (178,'Grease 2',1982,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (179,'Endangered Species',1982,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (180,'The Chosen',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (181,'Fast Times at Ridgemont High',1982,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (182,'A Little Sex',1982,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (183,'Diner',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (184,'Frances',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (185,'Angel',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (186,'Brimstone and Treacle',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (187,'Tron',1982,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (188,'Body Heat',1982,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (189,'Friday the 13th Part III',1982,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (190,'Before the Nickelodeon',1982,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (191,'Alone in the Dark',1982,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (192,'Vice Squad',1982,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (193,'The Soldier',1982,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (194,'Hawmps',1982,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (195,'Losin'' It',1982,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (196,'Zapped',1982,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (197,'Airplane II: The Sequel',1982,'Comd, Disa');
INSERT INTO film(fid,Title,yr,genre) VALUES (198,'Yol',1982,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (199,'At',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (200,'Driller Killer',1982,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (201,'Jekyll and Hyde...Together Again',1982,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (202,'House of the Long Shadows',1982,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (204,'Gregory''s Girl',1982,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (205,'Dragon Lord',1982,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (206,'The Final Option',1982,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (207,'I''m Dancing As Fast As I Can',1982,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (208,'Ca va faire mal',1982,'CnR,Comd');
INSERT INTO film(fid,Title,yr,genre) VALUES (209,'The Missionary',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (210,'Android',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (211,'Demons in the Garden',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (212,'Ein Sack Voll Flohe',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (213,'Feuer, Eis, und Dynamit',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (214,'Behind the Mosquito Net',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (215,'The Intruder',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (216,'Six Weeks',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (217,'The Last Horror Film',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (218,'Smithereens',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (219,'The House on Sorority Row',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (220,'Blind Chance',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (221,'Vigilante',1982,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (222,'The Principles of Hygiene and Safety in a Copper Mine',1982,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (223,'Personal Best',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (224,'Interrogation',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (225,'Tex',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (226,'Amityville II: The Possession',1982,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (227,'Parsifal',1982,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (228,'A Short Film About Killing',1982,'Noir');
INSERT INTO film(fid,Title,yr,genre) VALUES (229,'Dance with a Stranger',1982,'Noir');
INSERT INTO film(fid,Title,yr,genre) VALUES (231,'Another Way',1982,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (232,'Another Way',1982,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (233,'The Sedugenreion',1982,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (234,'The Adventurers of the Sierra Leone',1982,'West');
INSERT INTO film(fid,Title,yr,genre) VALUES (235,'Medea',1982,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (236,'Ariel',1983,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (237,'Boat People',1983,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (238,'The Old Well',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (239,'This is Spinal Tap',1983,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (240,'Valley Girl',1983,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (241,'Testament',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (242,'Yellowbeard',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (243,'To Be or Not To Be',1983,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (244,'My Tutor',1983,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (245,'Koyaanisqatsi',1983,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (246,'Love Letters',1983,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (247,'Silver Dream Racer',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (248,'We of the Never Never',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (249,'Against All Odds',1983,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (250,'The Hunger',1983,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (251,'Flashdance',1983,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (252,'Slayground',1983,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (253,'The Black Stallion Returns',1983,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (254,'Eddie Macon''s Run',1983,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (255,'Mickey''s Christmas Carol',1983,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (256,'Smokey and the Bandit III',1983,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (257,'National Lampoon''s Vacation',1983,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (259,'Lovesick',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (260,'Under Fire',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (261,'Psycho II',1983,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (262,'The Sting II',1983,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (263,'Short Time',1983,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (264,'Revenge of the Ninja',1983,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (265,'Young Warriors',1983,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (266,'Timerider: The Adventure of Lyle Swann',1983,'Agenren, ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (267,'Terry Fox Story',1983,'BioPx');
INSERT INTO film(fid,Title,yr,genre) VALUES (268,'The Big Chill',1983,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (269,'They Call Me Bruce',1983,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (270,'Local Hero',1983,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (271,'Get Crazy',1983,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (272,'Hell''s Angels Forever',1983,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (273,'Yentl',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (274,'Liquid Sky',1983,'Dram,Comd');
INSERT INTO film(fid,Title,yr,genre) VALUES (275,'Hercules',1983,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (276,'China Girl',1983,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (277,'Terms of Endearment',1983,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (278,'Killing of Angel Street',1983,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (279,'Cross Country',1983,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (280,'The Draughtsman''s Contragenre',1983,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (281,'Ogenreopussy',1983,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (282,'Never Cry Wolf',1983,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (283,'Divine Waters',1983,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (284,'Le juge',1983,'BioPic');
INSERT INTO film(fid,Title,yr,genre) VALUES (285,'Easy Money',1983,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (286,'Ich und Er',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (287,'The 4th Man',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (288,'Angelo My Love',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (289,'Dark Crystal',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (290,'Permanent Vacation',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (291,'Man of Flowers',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (292,'Deathgames',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (293,'Miles of Smiles, yrs of Struggle',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (294,'A Very Moral Night',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (295,'La Balance',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (296,'Ator the Fighting Eagle',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (297,'Bad Boys',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (298,'Angel',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (299,'Deep in the Heart',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (300,'Spring Break',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (301,'Portrait of a Hitman',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (302,'All the Right Moves',1983,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (303,'Olivia in Concert',1983,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (304,'Matter of Heart',1983,'Docu, BioB');
INSERT INTO film(fid,Title,yr,genre) VALUES (305,'The Concrete Jungle',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (306,'Il Deputado',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (307,'Rembetiko',1983,'Dram, Musc, BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (308,'I Promise to Remember',1983,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (309,'Buddy System',1983,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (310,'Anna to the Infinite Power',1983,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (311,'The Oresteia',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (312,'The Phantom of the Opera',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (313,'Fords on Water',1983,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (314,'Greystoke: The Legend of Tarzan, Lord of the Apes',1984,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (315,'Sixteen Candles',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (316,'Revolution',1984,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (317,'Sugar Cane Alley',1984,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (318,'The Price of Love',1984,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (319,'Diem Sum',1984,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (320,'Children of the Corn',1984,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (321,'Bachelor Party',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (322,'Highpoint',1984,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (323,'Hero',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (324,'Breakin''',1984,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (325,'Star Trek III: The Search For Spock',1984,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (326,'Racing with the Moon',1984,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (327,'Country',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (328,'D.C. Cab',1984,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (329,'Police Academy 2',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (330,'Police Academy',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (331,'Irreconcilable Differences',1984,'Romt, Comd');
INSERT INTO film(fid,Title,yr,genre) VALUES (332,'The Last Starfighter',1984,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (333,'Tightrope',1984,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (334,'Stranger Than Paradise',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (335,'Old Enough',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (336,'Reckless',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (337,'Romancing the Stone',1984,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (338,'Wet Gold',1984,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (339,'Champions',1984,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (340,'Two Minute Warning',1984,'Cops and Robbers');
INSERT INTO film(fid,Title,yr,genre) VALUES (341,'Ososhiki',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (342,'The Wild Life',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (343,'Hot Dog...The Movie',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (344,'C.H.U.D. II, Bud the Chud',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (345,'Weapons of the Spirit',1984,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (347,'The Razor''s Edge',1984,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (348,'Hambone and Hillie',1984,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (349,'Another Country',1984,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (350,'A Girl''s own Story',1984,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (351,'The Killing Fields',1984,'Dram,Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (352,'Razorback',1984,'Dram,Horr');
INSERT INTO film(fid,Title,yr,genre) VALUES (353,'The Company of Wolves',1984,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (354,'Terror in the Aisles',1984,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (356,'Cloak and Dagger',1984,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (357,'Making the Grade',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (358,'Repo Man',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (359,'The Adventures of Buckaroo Banzai: Across the 8th Dimension',1984,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (360,'A Woman''s Pale Blue Handwriting',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (361,'A Private Fungenreion',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (362,'The Family Game',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (363,'8 Men Out',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (364,'Lily in Love',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (365,'Sugarbaby',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (366,'Thus spake Bellavista',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (367,'Picone sent me',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (368,'Scandalous',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (369,'The Natural',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (370,'Savage Attragenreion',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (371,'Revenge of the Nerds',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (372,'Stranger''s Kiss',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (373,'Lassiter',1984,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (374,'The Times of Harvey Milk',1984,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (375,'Streetwise',1984,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (376,'The Good Fight',1984,'Ducu');
INSERT INTO film(fid,Title,yr,genre) VALUES (377,'Friday the 13th - The Final Chapter',1984,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (378,'Purple Rain',1984,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (379,'Hard to Hold',1984,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (381,'Dreamscape',1984,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (382,'Exterminator 2',1984,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (383,'Tango and Cash',1985,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (384,'The Breakfast Club',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (385,'Hamlet Goes Business',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (386,'Matador',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (387,'Matador',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (388,'Vampire ... Did you say Vampire?',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (389,'No Life King',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (390,'Desperately Seeking Susan',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (391,'A Nightmare on Elm Street Part Two: Freddy''s Revenge',1985,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (392,'Return of The Jedi',1985,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (393,'Orion''s Belt',1985,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (394,'Heaven Help Us',1985,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (395,'Jagged Edge',1985,'Myst');
INSERT INTO film(fid,Title,yr,genre) VALUES (396,'National Lampoon''s European Vacation',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (397,'Back to the Future',1985,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (398,'The Manhattan Projegenre',1985,'Susp, Romt');
INSERT INTO film(fid,Title,yr,genre) VALUES (399,'Shoah',1985,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (400,'Gleaming the Cube',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (401,'Blood Simple',1985,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (402,'Sudden Death',1985,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (403,'Runaway Train',1985,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (404,'A View to A Kill',1985,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (405,'The Living Daylights',1985,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (406,'The Black Cauldron',1985,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (407,'The Coca-Cola Kid',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (408,'Silverado',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (409,'Pee-Wee''s Big Adventure',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (410,'Police Story',1985,'Comd,Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (411,'A Zed and Two Naughts',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (412,'On the Edge',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (413,'The Gospel at Colonus',1985,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (414,'The Moon in the Gutter',1985,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (415,'The Reanimator',1985,'Hor');
INSERT INTO film(fid,Title,yr,genre) VALUES (417,'Desert Hearts',1985,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (418,'Defence of the Realm',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (419,'Blue Steel',1985,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (420,'A Chinese Ghost Story',1985,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (421,'Honoring Wallaby',1985,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (422,'Life on a String',1985,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (423,'The Best of Times',1985,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (424,'Tales from the Gimli Hospital',1985,'Comd,Horr');
INSERT INTO film(fid,Title,yr,genre) VALUES (425,'Zwei Fische auf dem Trockenen',1985,'Comd,Romt');
INSERT INTO film(fid,Title,yr,genre) VALUES (426,'Girls Just Want To Have Fun',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (427,'Hanussen',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (428,'Five Last Days',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (429,'Topos',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (430,'The Good Father',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (431,'Liberty, Equality, Sauerkraut',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (432,'Thirteen at Dinner',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (433,'Silver Bullet',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (434,'Cocktail Roadhouse',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (435,'The Adjuster',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (436,'Variety',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (437,'The Children of the Cold War',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (438,'Germany Pale Mother',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (439,'Inventory',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (440,'Bar Salon',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (441,'The Phiadelphia Attragenreion',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (442,'Town Alive',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (443,'Eubie!',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (444,'Gulag',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (445,'An Imaginary Tale',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (446,'The Hour of the Star',1985,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (447,'Las Madre The Mothers of the Plaza de Mayo',1985,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (448,'Blacks in the Military',1985,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (449,'Herbstmilch',1985,'Docu, Dram');
INSERT INTO film(fid,Title,yr,genre) VALUES (450,'The Rapture',1985,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (451,'Extramuros',1985,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (452,'Woman of the Port',1985,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (453,'The Quiet Earth',1985,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (454,'Les Amants du Pont-Neuf',1985,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (455,'Colonel Redl',1985,'Hist');
INSERT INTO film(fid,Title,yr,genre) VALUES (456,'Near Dark',1985,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (458,'Weird Science',1985,'ScFi, Romt');
INSERT INTO film(fid,Title,yr,genre) VALUES (459,'The Other Eye',1985,'prc');
INSERT INTO film(fid,Title,yr,genre) VALUES (460,'Flaming Creatures',1985,'prc');
INSERT INTO film(fid,Title,yr,genre) VALUES (461,'Locked-Up Time',1985,'prc');
INSERT INTO film(fid,Title,yr,genre) VALUES (462,'Platoon',1986,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (463,'Days of Thunder',1986,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (464,'Dreamchild',1986,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (465,'The Hand',1986,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (466,'White Nights',1986,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (467,'Signs of Wonder',1986,'Noir');
INSERT INTO film(fid,Title,yr,genre) VALUES (468,'Stand By Me',1986,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (469,'The Trip to Bountiful',1986,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (470,'I''ll Take Manhattan',1986,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (471,'An American Tail',1986,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (472,'Tough Guys',1986,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (473,'Just Between Friends',1986,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (474,'Poltergeist II',1986,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (475,'Police Academy 3',1986,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (476,'Pretty in Pink',1986,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (477,'Rent-a-Cop',1986,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (478,'Mona Lisa',1986,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (479,'Star Trek IV: The Voyage Home',1986,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (480,'The Juror',1986,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (481,'F/X',1986,'Susp, Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (482,'Down By Law',1986,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (483,'Street of Crocodiles',1986,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (484,'Top Gun',1986,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (485,'Peking Opera Blues',1986,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (486,'Therese',1986,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (487,'Sid and Nancy',1986,'BioPP');
INSERT INTO film(fid,Title,yr,genre) VALUES (488,'Say Yes',1986,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (489,'Armour of God',1986,'Comd,Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (490,'Dragons Forever',1986,'Comd,Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (491,'Dracula, He Wrote',1986,'Comd,Horr');
INSERT INTO film(fid,Title,yr,genre) VALUES (492,'Chronos',1986,'Docu,Epic');
INSERT INTO film(fid,Title,yr,genre) VALUES (493,'Two Friends',1986,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (494,'Psycho III',1986,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (495,'Crocodile Dundee',1986,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (496,'Frida: Naturaleza Vida',1986,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (497,'Out of Bounds',1986,'Cops and Robbers');
INSERT INTO film(fid,Title,yr,genre) VALUES (498,'Le paltoquet',1986,'Cops and Robbers');
INSERT INTO film(fid,Title,yr,genre) VALUES (499,'Les Fugitifs',1986,'Cops and Robbers');
INSERT INTO film(fid,Title,yr,genre) VALUES (500,'The Kidnapping of Mrs. Stone',1986,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (501,'Coupe de Ville',1986,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (502,'High Spirits',1986,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (503,'Law of Desire',1986,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (504,'Cagenreus',1986,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (505,'Make One',1986,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (506,'She-Devil',1986,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (507,'A Promise',1986,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (508,'The White Rose',1986,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (509,'America and Lewis Hine',1986,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (510,'Maximum Overdrive',1986,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (511,'Half of Heaven',1986,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (512,'Twilight of the Cockroaches',1987,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (513,'Three Men and A Baby',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (514,'Planes, Trains, and Automobiles',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (515,'River''s Edge',1987,'Docu,Dram');
INSERT INTO film(fid,Title,yr,genre) VALUES (516,'Celia',1987,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (517,'Dark Eyes',1987,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (518,'Glory Days',1987,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (519,'The Stepfather',1987,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (520,'She''s Gotta Have It',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (521,'Hamburger Hill',1987,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (522,'Raising Arizona',1987,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (523,'My Life As a Dog',1987,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (524,'Overboard',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (525,'Beverly Hills Cop II',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (526,'Broadcast News',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (527,'Tin Men',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (528,'Tin Men',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (529,'Tampopo',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (530,'La Bamba',1987,'Docu,Musc');
INSERT INTO film(fid,Title,yr,genre) VALUES (531,'Slam Dance',1987,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (532,'Imagen Latente',1987,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (533,'Murder Ordained',1987,'Dram, BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (534,'The Princess Bride',1987,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (535,'Batteries Not Included',1987,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (536,'Dirty Dancing',1987,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (537,'Making Mr.~Right',1987,'Romt,ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (538,'The Belly of an Architegenre',1987,'Surr');
INSERT INTO film(fid,Title,yr,genre) VALUES (539,'The Icycle Thief',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (540,'Vincent - The Life and Times of Vincent Van Gogh',1987,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (541,'Theophilos',1987,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (542,'Revenge of the Nerds II',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (543,'Rita, Sue and Bob Too',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (544,'Hollywood Shuffle',1987,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (545,'What Have I Done to Deserve This?',1987,'Comd, Dram');
INSERT INTO film(fid,Title,yr,genre) VALUES (546,'Johnny Be Good',1987,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (547,'Wish You Were Here',1987,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (548,'House of Games',1987,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (549,'Projegenre X',1987,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (550,'Cry and Cry Again',1987,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (551,'Less Than Zero',1987,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (552,'The Emperor''s Naked Army Marches On',1987,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (553,'Naga Bonar',1987,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (554,'Couples and Robbers',1987,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (555,'Radio Bikini',1987,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (556,'Matewan',1987,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (557,'Black Champions',1987,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (558,'A League of their Own',1987,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (559,'The Children of the Helidona',1987,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (560,'Tough Guys Don''t Dance',1987,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (561,'Mauvais Sang',1987,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (562,'Das Leben ist ein langer, ruhiger Fluss',1987,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (563,'Local Stigmatic',1987,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (564,'I''ve Heard the Mermaids Singing',1987,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (565,'Clownhouse',1987,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (566,'Creepshow 2',1987,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (567,'The Running Man',1987,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (568,'The Miracle of Love',1987,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (569,'The yr my Voice Broke',1987,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (570,'Testimony',1987,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (571,'Mala Noche',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (572,'Buster',1988,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (573,'Pelle the Conqueror',1988,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (574,'Ferris Buellers Day off',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (575,'Figenreitious Marriage',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (576,'Little Dorrit',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (577,'Things Change',1988,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (578,'Chocolat',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (579,'Off Limits',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (580,'Punchline',1988,'Romt Comd');
INSERT INTO film(fid,Title,yr,genre) VALUES (581,'Alien Nation',1988,'ScFi,CA');
INSERT INTO film(fid,Title,yr,genre) VALUES (583,'The Wizards of Loneliness',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (584,'License Revoked',1988,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (585,'Beetlejuice',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (586,'Burning Secret',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (587,'Let''s Get Lost',1988,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (588,'Rehearsals for Extingenre Anatomies',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (589,'Crocodile Dundee II',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (590,'Igla',1988,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (591,'Agenre of Piracy',1988,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (592,'Die Hard',1988,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (593,'Romero',1988,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (594,'White Mischief',1988,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (595,'Who Framed Roger Rabbit',1988,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (596,'Akira',1988,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (597,'The Land Before Time',1988,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (598,'Women on the Verge of A Nervous Breakdown',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (599,'Casual Sex',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (600,'When Twins are Interchanged',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (601,'A Taxing Woman',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (602,'Funny',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (603,'The Naked Gun',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (604,'Police Story II',1988,'Comd,Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (605,'Wall Street',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (606,'Ratboy',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (607,'School Daze',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (608,'Reunion at Fairborough',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (609,'Oliver & Company',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (610,'Rain Man',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (611,'Memories of Me',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (612,'Far North',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (613,'The Milagro Beanfield War',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (614,'Tequila Sunrise',1988,'Myst');
INSERT INTO film(fid,Title,yr,genre) VALUES (616,'Babette''s Feast',1988,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (617,'Fatal Attragenreion',1988,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (618,'Bull Durham',1988,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (619,'Dealers',1988,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (620,'The Bedroom Window',1988,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (621,'Robocop',1988,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (622,'Code of Silence',1988,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (623,'Above the Law',1988,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (624,'Bal Poussi\`ere',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (625,'\UN',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (626,'Les maris, les femmes, les amants',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (627,'The Yen Family',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (628,'Heartbreak Hotel',1988,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (629,'A Month in the Country',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (630,'Throw Momma from the Train',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (631,'Mr.~North',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (632,'Dreams of Hind and Camilla',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (633,'Diary for My Loves',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (634,'Everybody''s All-American',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (635,'The Good Mother',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (636,'The Good Mother',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (637,'Stripped to Kill',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (638,'Surf II',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (639,'The Fly II',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (640,'Running Hot',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (641,'The New Kids',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (642,'Code Name: Emerald',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (643,'Some Kind of Wonderful',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (644,'Sister Sister',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (645,'Manifesto',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (646,'Haunted Summer',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (647,'Illegally Yours',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (648,'Powaqqatsi',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (649,'Stormy Monday',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (650,'High Season',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (651,'Decalogue',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (652,'Rama Dama',1988,'Docu, Dram');
INSERT INTO film(fid,Title,yr,genre) VALUES (653,'To Kill A Priest',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (654,'Fabula de la Bella Palomera',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (655,'Deserter',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (656,'Johann Strauss, The King without a Crown',1988,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (657,'Drowning By Numbers',1988,'Noir, Comd');
INSERT INTO film(fid,Title,yr,genre) VALUES (658,'Goguktu Ve Yagmur Ciseliyorau',1988,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (659,'The Summer of Miss Forbes',1988,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (660,'Ein kurzer Film Uber die Liebe',1988,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (661,'D.O.A.',1988,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (662,'Nightsongs',1988,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (663,'Queenie, the Star of Calcutta',1988,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (664,'Raggedy Rawney',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (665,'Looking for Langston',1989,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (666,'My Left Foot',1989,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (667,'Camille Claudel',1989,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (668,'Uncle Buck',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (669,'Oblomov',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (670,'Purple Haze',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (671,'Comic Book Confidential',1989,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (672,'Henry V',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (673,'Life is Cheap, but Toilet Paper is Expensive',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (674,'A Dry White Season',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (675,'36 Fillette',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (676,'Field of Dreams',1989,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (677,'Phantom of the Opera',1989,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (678,'Apartment Zero',1989,'Noir');
INSERT INTO film(fid,Title,yr,genre) VALUES (679,'The Match Fagenreory Girl',1989,'Noir, Comd');
INSERT INTO film(fid,Title,yr,genre) VALUES (680,'The Wizard',1989,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (681,'Eat a Bowl of Tea',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (682,'The Fabulous Baker Boys',1989,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (683,'Blaze',1989,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (684,'Cookie',1989,'Comd,Susp');
INSERT INTO film(fid,Title,yr,genre) VALUES (685,'Meet the Applegates',1989,'ScFi,Comd');
INSERT INTO film(fid,Title,yr,genre) VALUES (686,'We''re No Angels',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (687,'The Accidental Tourist',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (688,'Batman',1989,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (689,'Pet Sematary',1989,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (690,'Back to the Future Part II',1989,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (691,'Scandal',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (692,'Kitchen Sink',1989,'Comd, Romt');
INSERT INTO film(fid,Title,yr,genre) VALUES (693,'Tetsuo, the Iron Man',1989,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (694,'Earth Girls Are Easy',1989,'|');
INSERT INTO film(fid,Title,yr,genre) VALUES (695,'The Four Deuces',1989,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (696,'Angel Town',1989,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (697,'Born on the Fourth of July',1989,'Agenren');
INSERT INTO film(fid,Title,yr,genre) VALUES (698,'License To Kill',1989,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (699,'Fat Man and Little Boy',1989,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (700,'Stand and Deliver',1989,'BioP');
INSERT INTO film(fid,Title,yr,genre) VALUES (701,'Glory',1989,'BioP,Advt');
INSERT INTO film(fid,Title,yr,genre) VALUES (702,'The Little Mermaid',1989,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (703,'All Dogs Go To Heaven',1989,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (704,'Do The Right Thing',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (705,'National Lampoon''s Last Resort',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (706,'La Legenrerice',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (707,'Good Morning, Vietnam',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (708,'Work Experience',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (709,'Big',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (710,'Heathers',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (711,'The War of the Roses',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (712,'Vampire''s Kiss',1989,'Comd,Noir');
INSERT INTO film(fid,Title,yr,genre) VALUES (713,'A Taxing Woman''s Return',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (714,'Drugstore Cowboy',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (715,'Cannibal Tours',1989,'Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (716,'The Wash',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (717,'Paint it Black',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (718,'Mystery Train',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (719,'Old Gringo',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (720,'Jacknife',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (721,'Ikili Oyunlar',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (722,'Harlem Nights',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (723,'Nightbreaker',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (724,'Dad',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (725,'Cinema Paradiso',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (726,'Raspad',1989,'Dram, Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (727,'Hay Algo Alla Afuera',1989,'Fant');
INSERT INTO film(fid,Title,yr,genre) VALUES (728,'Edward Scissorhands',1989,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (729,'Star Trap',1989,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (730,'The Music Teacher',1989,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (731,'When Harry Met Sally',1989,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (732,'Men Don''t Leave',1989,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (733,'Bagdad Cafe',1989,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (734,'Star Trek V: The Final Frontier',1989,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (735,'Honey, I Shrunk the Kids',1989,'ScFi,Comd');
INSERT INTO film(fid,Title,yr,genre) VALUES (736,'Hostage Flight',1989,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (737,'Patriot Games',1989,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (738,'The Turn of the Screw',1989,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (739,'Notorious',1989,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (740,'Fear',1989,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (741,'Dead Calm',1989,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (742,'FX2',1989,'Adventure');
INSERT INTO film(fid,Title,yr,genre) VALUES (743,'Everything''s for you',1989,'Cart');
INSERT INTO film(fid,Title,yr,genre) VALUES (744,'Ripoux contre Ripoux',1989,'Cops and Robbers');
INSERT INTO film(fid,Title,yr,genre) VALUES (745,'Tapeheads',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (746,'Parents',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (747,'The Big Pigenreure',1989,'Comedy');
INSERT INTO film(fid,Title,yr,genre) VALUES (748,'Best of the Best',1989,'Comd, Dram');
INSERT INTO film(fid,Title,yr,genre) VALUES (749,'The Adventures of Ford Fairlane',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (750,'Jesus of Montreal',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (751,'The Supernaturals',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (752,'The Guard',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (753,'Say Anything',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (754,'Zero City',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (755,'Out Cold',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (756,'Paper Wedding',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (757,'Let It Be',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (758,'American Psycho',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (759,'A Woman''s Tale',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (760,'In Glass',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (761,'Never, Nowhere, To No-one',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (762,'Scugnizzi',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (763,'Woman of Courage',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (764,'Cousins',1989,NULL);
INSERT INTO film(fid,Title,yr,genre) VALUES (765,'Eh'' die Fledermaus ihren Flug Beendet',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (766,'Children of a Lesser God',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (767,'Angry Harvest',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (768,'Underground',1989,'Drama');
INSERT INTO film(fid,Title,yr,genre) VALUES (769,'Coming Out',1989,'Dram,Docu');
INSERT INTO film(fid,Title,yr,genre) VALUES (770,'La Chiesa',1989,'Horror');
INSERT INTO film(fid,Title,yr,genre) VALUES (771,'Nutcracker, the Motion Pigenreure',1989,'Music');
INSERT INTO film(fid,Title,yr,genre) VALUES (772,'Frau Berta Garlan',1989,'Romantic');
INSERT INTO film(fid,Title,yr,genre) VALUES (773,'The Navigator',1989,'ScFi');
INSERT INTO film(fid,Title,yr,genre) VALUES (774,'Withnail and I',1989,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (775,'True Believer',1989,'Suspense');
INSERT INTO film(fid,Title,yr,genre) VALUES (776,'Flashback',1989,'TV, Dram');
INSERT INTO film(fid,Title,yr,genre) VALUES (777,'The Kill Off',1989,'West');
