INSERT INTO studio(sid,sname,company,City,Country) VALUES (19,'20th Cent.','Twentieth Century','Hollywood','CA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (22,'20th Cent.','20th Century Productions','Century City?','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (45,'AIP','American International Pictures',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (13,'Allied','Allied Artists','Los Angeles','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (44,'ARC','American Releasing Corporation','Palo Alto','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (69,'Astor','indep',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (17,'ATP','Associated Talking Pictures',NULL,'England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (82,'Bavaria','Bavaria Atelier','Munchen','F.R.Germany');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (65,'Biograph',NULL,'The Bronx','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (111,'Black Lion','ITV','London','England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (55,'Box Office','Box Office International',NULL,'France');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (112,'Brent Walker',NULL,'London','England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (98,'Buena Vista','Disney',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (105,'Caravan',NULL,NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (90,'Carolco',NULL,'North-carolina','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (80,'Carosse','Films du Carosse','Paris','France');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (117,'Castle Rock','Warners',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (104,'CastleRock',NULL,NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (58,'Cathay','Cathay Film Company','HongKong','China');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (9,'Cines',NULL,NULL,'Italy');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (64,'Cines',NULL,NULL,'Italy');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (33,'Cinetone','NV Filmex','Amsterdam','Holland');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (96,'Cobra','Cobra Filmproduktion',NULL,'Ge');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (2,'Columbia','Columbia Pictures','Burbank','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (74,'Condor','Deutsche Condor Film GmbH','Munchen','F.R.Germany');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (40,'DEFA','D.R.Germany','Berlin','D.R.Germany');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (108,'Disney',NULL,'Burbank','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (92,'Double','Double Head',NULL,'Australia');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (41,'Eagle Lion','Eagle Lion',NULL,NULL);
INSERT INTO studio(sid,sname,company,City,Country) VALUES (63,'Eagle Lion','Rank',NULL,NULL);
INSERT INTO studio(sid,sname,company,City,Country) VALUES (11,'Elstree','British International Pictures','Elstree','England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (7,'Emelka',NULL,'Munich','Germany');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (37,'ENSA','Entertainment National Service Association',NULL,'England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (81,'Essexe','Essex Productions',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (84,'Fantasy',NULL,'Berkely CA','U.S.A.');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (79,'Film House','The Film House','Melbourne','Australia');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (46,'Filmgroup','American International Pictures',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (66,'FilmMakers','Film Makers',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (77,'Filmservice',NULL,'Los Angeles','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (94,'Filmways','Filmways',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (34,'First National','Warner Brothers',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (27,'Fox','20th Cent.Fox','Century City','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (3,'Gainsborough','Gainsborough',NULL,'England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (99,'Galaxie','Les Films Galaxie',NULL,'France');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (24,'GFD','Gaumont British',NULL,'England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (57,'Golden Harvest','Golden Harvest Studio','HongKong','China');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (16,'Goldwyn','Sam Goldwyn Productions',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (103,'Gracie',NULL,'Hollywood','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (89,'Granada',NULL,NULL,'England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (48,'Hallmark','American International Pictures',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (70,'Howco','indep',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (113,'ITC','ITV','London','England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (30,'Korda','Korda','Denham','England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (75,'laPleiade','Films de la Pleiade',NULL,'France');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (100,'Lee Rich','Lee Rich Productions, Warners',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (18,'Lime Grove','Gaumont British',NULL,'England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (6,'Lion','British Lion','London','UK');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (71,'Lippert','indep',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (20,'London','London Films - Korda','London','England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (61,'London Films',NULL,'London','England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (97,'Lorimar',NULL,NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (115,'Lucasfilm','Disney','San Francisco','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (51,'Malpaso','Malpaso Productions','Hollywood','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (106,'MCA','Matsushita',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (4,'Merabpomfilm','Me\v rabpomfil''m','Moscow','USSR');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (28,'MGM','Metro-Goldwyn-Mayer',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (68,'MGM British','Metro-Goldwyn-Mayer','Elstree','England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (87,'MGM-U.A','MGM-U.A. Communications Co.','Hollywood','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (95,'Miramax',NULL,NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (25,'Monogram','Allied Artists','Hollywood','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (36,'NEF','Novelles Editions Francaises','Paris','France');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (14,'Nero','Nero Film A.G.','Berlin','Germany');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (42,'New World',NULL,'Rome','Italy');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (102,'NewLine','New Line Cinema',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (52,'NFDC','National Film Development Corp.','New Delhi','India');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (83,'NWP','New World Pictures','Hollywood','U.S.A.');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (110,'Orion','MGM','Los Angeles','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (39,'Paramount','Paramount Corp.','Los Angeles','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (15,'Paris',NULL,'Paris','France');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (62,'Pathe 2','Pathe Communications',NULL,'Italy');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (88,'Paulist','Paulist Pictures','Malibu CA','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (32,'Pinewood','Gainsborough',NULL,'England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (10,'PRC','Producers Releasing Corporation',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (59,'Producers Distr.Corp',NULL,NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (5,'Prometheus','Int.Arbeiterhilfe',NULL,'Germany');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (72,'RealArt','indep',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (23,'Reliance',NULL,'LA','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (26,'Republic','Republic Film Corporation','San Fernando, Hollywood','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (50,'Revue','MCA','Universal City','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (12,'RKO','RKO Radio','Hollywood','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (38,'Roach','Roach Studios','Hollywwood','CA,USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (31,'Selznick',NULL,'Hollywood','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (78,'Shamley','Paramount','Los Angeles','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (116,'Showtime','CBS','Dublin','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (114,'Svenska ord',NULL,NULL,'Sweeden');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (35,'Teddington','Warner Brothers, First National','London','England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (91,'Thames',NULL,NULL,'England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (85,'Todrest',NULL,NULL,'France');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (47,'Trans-American','American International Pictures',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (43,'Transatlantic','Transatlantic','London','England');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (101,'TriStar','Tri-Star Pictures Inc.',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (21,'UFA','UFI','Neubabelsberg','Germany');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (54,'UFA','Bertelsmann','Babelsberg','F.R.Germany');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (49,'UFA 2','UFA, F.R.Germany','Babelsberg','F.R.Germany');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (29,'UFI','Nazi Government',NULL,'Germany');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (73,'UGC','Union Generale Cinamatographique',NULL,'France');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (107,'Universal',NULL,NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (8,'Vitaphone','Warners and Western Electric',NULL,'USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (119,'Vestron','Lion''s Gate','Stamford','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (1,'Warners','Warner Bros.','Burbank','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (67,'Woodfall','Woodfall Productions',NULL,'G.B.');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (86,'Xian Film Studios','P.R.China','Xian Shaanxi','P.R.China');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (53,'Zoetrope','Warners','San Francisco','USA');
INSERT INTO studio(sid,sname,company,City,Country) VALUES (120,'Zenith','Central Televison',NULL,'England');
